C_Algorithms: misc/src/dynamicFib.c File Reference
dynamicFib.c File Reference
#include <stdio.h>
#include "dynamicFib.h"
Functions
long DynFib (int n)
DynFib is a function that is calculating the fibonacci number dynamic. It's a lot faster as the recursive Version especally with bigger numbers.
void DynamicFib (int number)
Prints the return value of the called function RecFib.
Function Documentation
DynamicFib()
void DynamicFib (int number)
Prints the return value of the called function RecFib.
Parameters
number
Definition at line 31 of file dynamicFib.c.
{
    printf("%ld\n", DynFib(number));
}
References DynFib().
Referenced by FunctionCall().
DynFib()
long DynFib (int n)
DynFib is a function that is calculating the fibonacci number dynamic. It's a lot faster as the recursive Version especally with bigger numbers.
Parameters
n input as an int
Returns
long Returns the nth fibonacci number
Definition at line 12 of file dynamicFib.c.
{
    if (n <= 2)
        return 1;
    long array[n - 1];
    array[0] = 1; // Basevalue for fibonacci 1 = 1
    array[1] = 1; // Basevalue for fibonacci 2 = 1
    // Safe value from the n th fibonacci number in array[n - 1]
    for (long i = 2; i < n; i++)
        array[i] = array[i - 1] + array[i - 2];
    return array[n - 1]; // Return the value
}
Referenced by DynamicFib().