C_Algorithms: memory/include/queue.h File Reference
queue.h File Reference
#include <stdint.h>
#include <math.h>
#include <stdbool.h>
Data Structures
struct queue
Macros
#define QUEUE_NO_VALUE (queue_value_t)INFINITY
Typedefs
typedef float queue_value_t
typedef struct queue myqueue_t
Functions
myqueue_t * CreateQueue (uint32_t capacity)
Create a Queue object.
myqueue_t * FreeQueue (myqueue_t *queue)
Delete Queue object.
bool QueueIsEmpty (myqueue_t *queue)
Check if Queue is empty.
bool QueueIsFull (myqueue_t *queue)
Check if Queue is full.
void PushQueue (myqueue_t *queue, queue_value_t value)
Put new data in the Queue object.
queue_value_t PopQueue (myqueue_t *queue)
Delete data from Queue object.
queue_value_t FrontQueue (myqueue_t *queue)
First value of the Queue.
queue_value_t BackQueue (myqueue_t *queue)
Last element of the Queue.
void PrintQueue (myqueue_t *queue)
Print the whole queue.
void Queue ()
Macro Definition Documentation
QUEUE_NO_VALUE
#define QUEUE_NO_VALUE (queue_value_t)INFINITY
Definition at line 10 of file queue.h.
Referenced by BackQueue(), FrontQueue(), and PopQueue().
Typedef Documentation
myqueue_t
typedef struct queue myqueue_t
queue_value_t
typedef float queue_value_t
Definition at line 9 of file queue.h.
Function Documentation
BackQueue()
queue_value_t BackQueue (myqueue_t * queue)
Last element of the Queue.
Parameters
queue
Returns
queue_value_t
Definition at line 133 of file queue.c.
{
    if (QueueIsEmpty(queue))
        return QUEUE_NO_VALUE;
    return queue->data[queue->back_id];
}
References queue::back_id, queue::data, QUEUE_NO_VALUE, and QueueIsEmpty().
CreateQueue()
myqueue_t * CreateQueue (uint32_t capacity)
Create a Queue object.
Parameters
capacity
Returns
myqueue_t*
Definition at line 13 of file queue.c.
{
    myqueue_t *queue = (myqueue_t *)malloc(sizeof(myqueue_t));
    if (queue == NULL)
        return NULL;
    size_t data_size = capacity * sizeof(queue_value_t);
    queue_value_t *data = (queue_value_t *)malloc(data_size);
    if (data == NULL)
    {
        free(queue);
        return NULL;
    }
    queue->front_id = 0u;
    queue->back_id = capacity-1;
    queue->capacity = capacity;
    queue->size = 0u;
    queue->data = data;
    return queue;
}
References queue::back_id, queue::capacity, queue::data, queue::front_id, and queue::size.
Referenced by Queue().
FreeQueue()
myqueue_t * FreeQueue (myqueue_t * queue)
Delete Queue object.
Parameters
queue
Returns
myqueue_t*
Definition at line 44 of file queue.c.
{
    if (queue != NULL)
    {
        if (queue->data != NULL)
        {
            free(queue->data);
        }
        free(queue);
    }
    return NULL;
}
References queue::data.
Referenced by Queue().
FrontQueue()
queue_value_t FrontQueue (myqueue_t * queue)
First value of the Queue.
Parameters
queue
Returns
queue_value_t
Definition at line 120 of file queue.c.
{
    if (QueueIsEmpty(queue))
        return QUEUE_NO_VALUE;
    return queue->data[queue->front_id];
}
References queue::data, queue::front_id, QUEUE_NO_VALUE, and QueueIsEmpty().
PopQueue()
queue_value_t PopQueue (myqueue_t * queue)
Delete data from Queue object.
Parameters
queue
Returns
queue_value_t
Definition at line 103 of file queue.c.
{
    if (QueueIsEmpty(queue))
        return QUEUE_NO_VALUE;
    queue_value_t value = queue->data[queue->front_id];
    queue->front_id = (queue->front_id + 1u) % queue->capacity;
    queue->size--;
    return value;
}
References queue::capacity, queue::data, queue::front_id, QUEUE_NO_VALUE, QueueIsEmpty(), and queue::size.
PrintQueue()
void PrintQueue (myqueue_t * queue)
Print the whole queue.
Parameters
queue
Definition at line 145 of file queue.c.
{
    if (queue == NULL)
        return;
    printf(
        "The queue contains %u elements with a capacity of %u.\n",
        queue->size,
        queue->capacity
    );
    for (int32_t i = 0; i < queue->size; i++)
    {
        printf("Index: %d, Value %f\n", i, queue->data[i]);
    }
}
References queue::capacity, queue::data, and queue::size.
Referenced by Queue().
PushQueue()
void PushQueue (myqueue_t * queue, queue_value_t value)
Put new data in the Queue object.
Parameters
queue
value
Definition at line 87 of file queue.c.
{
    if (QueueIsFull(queue))
        return;
    queue->back_id = (queue->back_id + 1u) % queue->capacity;
    queue->data[queue->back_id] = value;
    queue->size++;
}
References queue::back_id, queue::capacity, queue::data, QueueIsFull(), and queue::size.
Referenced by Queue().
Queue()
void Queue ()
Definition at line 163 of file queue.c.
{
    uint32_t capacity = 4u;
    myqueue_t *queue = CreateQueue(capacity);
    PushQueue(queue, 2.0f);
    PushQueue(queue, 3.0f);
    PrintQueue(queue);
    queue = FreeQueue(queue);
}
References CreateQueue(), FreeQueue(), PrintQueue(), and PushQueue().
Referenced by FunctionCall().
QueueIsEmpty()
bool QueueIsEmpty (myqueue_t * queue)
Check if Queue is empty.
Parameters
queue
Returns
true
false
Definition at line 64 of file queue.c.
{
    return (queue->size == 0u);
}
References queue::size.
Referenced by BackQueue(), FrontQueue(), and PopQueue().
QueueIsFull()
bool QueueIsFull (myqueue_t * queue)
Check if Queue is full.
Parameters
queue
Returns
true
false
Definition at line 76 of file queue.c.
{
    return (queue->size == queue->capacity);
}
References queue::capacity, and queue::size.
Referenced by PushQueue().