C_Algorithms: misc/src/recursiveFib.c File Reference
recursiveFib.c File Reference
#include <stdio.h>
#include "recursiveFib.h"
Functions
int RecFib (int n)
RecFib is a function wihich can calculate the fibonacci number by calling it self n times.
void RecursiveFib (int number)
Prints the return value of the called function RecFib.
Function Documentation
RecFib()
int RecFib (int n)
RecFib is a function wihich can calculate the fibonacci number by calling it self n times.
Parameters
n Input as a sting
Returns
int returns the nth fibonacci number
Definition at line 13 of file recursiveFib.c.
{
  if(n <= 2)
    return 1;
  return RecFib(n - 1) + RecFib(n - 2);
}
References RecFib().
Referenced by RecFib(), and RecursiveFib().
RecursiveFib()
void RecursiveFib (int number)
Prints the return value of the called function RecFib.
Parameters
number
Definition at line 25 of file recursiveFib.c.
{
  printf("%d\n", RecFib(number));
}
References RecFib().
Referenced by FunctionCall().