C_Algorithms: memory/src/stack.c File Reference
stack.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "stack.h"
Functions
mystack_t * CreateStack (uint32_t capacity)
Create a Stack object.
mystack_t * FreeStack (mystack_t *stack)
Free the memory of a given Stack object.
bool StackIsEmpty (mystack_t *stack)
Check if the Stack object is empty.
bool StackIsFull (mystack_t *stack)
Check if the Stack object is full.
void PushStack (mystack_t *stack, stack_value_t value)
Push a new object to the stack.
stack_value_t PopStack (mystack_t *stack)
Pop the object on top of the stack.
stack_value_t TopStack (mystack_t *stack)
Return the top object of the stack.
void PrintStack (mystack_t *stack)
Print the whole stack.
void Stack ()
Function Documentation
CreateStack()
mystack_t * CreateStack (uint32_t capacity)
Create a Stack object.
Parameters
capacity
Returns
stack_t*
Definition at line 14 of file stack.c.
{
    mystack_t *stack = (mystack_t *)malloc(sizeof(mystack_t));
    if (stack == NULL)
        return NULL;
    size_t data_size = capacity * sizeof(stack_value_t);
    stack_value_t *data = (stack_value_t *)malloc(data_size);
    if (data == NULL)
    {
        free(stack);
        return NULL;
    }
    stack->capacity = capacity;
    stack->size = 0u;
    stack->data = data;
    return stack;
}
References stack::capacity, stack::data, and stack::size.
Referenced by Stack().
FreeStack()
mystack_t * FreeStack (mystack_t * stack)
Free the memory of a given Stack object.
Parameters
stack
Returns
stack_t*
Definition at line 43 of file stack.c.
{
    if (stack != NULL)
    {
        if (stack->data != NULL)
        {
            free(stack->data);
        }
        free(stack);
    }
    return NULL;
}
References stack::data.
Referenced by Stack().
PopStack()
stack_value_t PopStack (mystack_t * stack)
Pop the object on top of the stack.
Parameters
stack
Returns
stack_value_t
Definition at line 102 of file stack.c.
{
    if (StackIsEmpty(stack))
        return STACK_NO_VALUE;
    stack->size--;
    return stack->data[stack->size];
}
References stack::data, stack::size, STACK_NO_VALUE, and StackIsEmpty().
PrintStack()
void PrintStack (mystack_t * stack)
Print the whole stack.
Parameters
stack
Definition at line 129 of file stack.c.
{
    if (stack == NULL)
        return;
    printf(
        "The stack contains %u elements with a capacity of %u.\n",
        stack->size,
        stack->capacity
    );
    for (int32_t i = 0; i < stack->size; i++)
    {
        printf("Index: %d, Value %f\n", i, stack->data[i]);
    }
}
References stack::capacity, stack::data, and stack::size.
Referenced by Stack().
PushStack()
void PushStack (mystack_t * stack, stack_value_t value)
Push a new object to the stack.
Parameters
stack
Definition at line 85 of file stack.c.
{
    if (StackIsFull(stack))
    {
        return;
    }
    stack->data[stack->size] = value;
    stack->size++;
}
References stack::data, stack::size, and StackIsFull().
Referenced by Stack().
Stack()
void Stack ()
Definition at line 148 of file stack.c.
{
    uint32_t capacity = 4u;
    mystack_t *stack = CreateStack(capacity);
    PushStack(stack, 2.0f);
    PushStack(stack, 3.0f);
    PrintStack(stack);
    stack = FreeStack(stack);
}
References CreateStack(), FreeStack(), PrintStack(), and PushStack().
Referenced by FunctionCall().
StackIsEmpty()
bool StackIsEmpty (mystack_t * stack)
Check if the Stack object is empty.
Parameters
stack
Returns
true
false
Definition at line 63 of file stack.c.
{
    return (stack->size == 0u);
}
References stack::size.
Referenced by PopStack(), and TopStack().
StackIsFull()
bool StackIsFull (mystack_t * stack)
Check if the Stack object is full.
Parameters
stack
Returns
true
false
Definition at line 75 of file stack.c.
{
    return (stack->size == stack->capacity);
}
References stack::capacity, and stack::size.
Referenced by PushStack().
TopStack()
stack_value_t TopStack (mystack_t * stack)
Return the top object of the stack.
Parameters
stack
Returns
stack_value_t
Definition at line 117 of file stack.c.
{
    if (StackIsEmpty(stack))
        return STACK_NO_VALUE;
    return stack->data[stack->size - 1];
}
References stack::data, stack::size, STACK_NO_VALUE, and StackIsEmpty().