name: Build and Run Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake, Clang and Conan
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang
        sudo apt-get install -y python3-pip
        sudo apt-get install -y tree
        pip3 install conan

    - name: Set Conan Profile
      run: conan profile detect --force

    - name: Install dependencies
      run: conan install . -s build_type=Release --build=missing

    - name: Generate build files
      run: cmake -B ${{github.workspace}} -DCONAN=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: cmake --build ${{github.workspace}} --config Release

    # If you want to run the executable add this step
    - name: Run the executable
      run: /build/test/test_exec

    # For a clean build, you can prepend the build step with `--clean-first`
    # - name: Clean build
    #   run: cmake --build build --clean-first