name: Build and Run Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: conanio/gcc9
      options: --user root

    steps:
    - uses: actions/checkout@v4

    - name: Set Conan Profile
      run: |
        conan profile new --detect default
        conan profile update settings.compiler.libcxx=libstdc++17 default
        conan profile update settings.build_type=Release default

    - name: Install dependencies
      run: conan install . -s build_type=Release -o build --build=missing

    - name: Generate build files
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCONAN=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build the project
      run: cmake --build build

    # If you want to run the executable add this step
    - name: Run the executable
      run: cmake --build build --target runTest

    # For a clean build, you can prepend the build step with `--clean-first`
    # - name: Clean build
    #   run: cmake --build build --clean-first